[project]
name = "taxi-rides-ny"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-duckdb>=1.10.0",
    "duckdb>=1.4.4",
    "httpx>=0.28.0",
    "rich>=13.9.0",
]
